name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04      
    steps:
      - uses: actions/checkout@v3
      - uses: juliangruber/read-file-action@v1
        id: cowsay_output_id # You want id
        with:
          path: ./README.md
          
      - uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: "${{ steps.cowsay_output_id.outputs.content }}"
      
        